name: Build (Linux)

on:
  push:
    branches:
      - 5.x.x-stable
  pull_request:
    branches:
      - 5.x.x-stable

jobs:
  build:
    runs-on: ubuntu-22.04

    services:
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Get dependencies
        run: make deps
      - name: Test with NIO
        run: ./mvnw verify -P '!setup-test-cluster,use-nio' -Drabbitmqctl.bin=DOCKER:${{job.services.rabbitmq.id}} -Dit.test=ClientTests,FunctionalTests,ServerTests
      - name: Test with blocking IO
        run: ./mvnw verify -P '!setup-test-cluster' -Drabbitmqctl.bin=DOCKER:${{job.services.rabbitmq.id}} -Dit.test=ClientTests,FunctionalTests,ServerTests